#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Mar 20 21:56:33 2023

@author: batman
"""

import numpy as np
import matplotlib.pyplot as plt

# Define the x-axis range
x = np.linspace(-10, 10, 1000)

# Define the beam parameters
w0 = 2  # beam waist
zR = np.pi * w0**2 / 1064e-9  # Rayleigh range
z = 0.2 * zR  # distance from waist

# Calculate the beam radius
w = w0 * np.sqrt(1 + (z / zR)**2)

# Calculate the intensity profile
I = (w0 / w)**2 * np.exp(-2 * x**2 / w**2)

# Plot the intensity profile
plt.plot(x, I)
plt.xlabel('x (mm)')
plt.ylabel('Intensity (W/m^2)')
plt.title('Spatial Profile of Laser Beam')
plt.show()
